export const pdfData = {
    "Health Insurance": {
        "Acko": {
          "Standard Health": "/Documents/HealthInsurance/Acko/Policy Wording/Platinum+Health-Policy+wording.pdf",
          "Platinum Health": "/Documents/HealthInsurance/Acko/Policy Wording/Standard+Health-Policy+wording.pdf",
        },
        "ADITYA BIRLA": {
          "Activ Care Premier": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ Care Premier.pdf",
          "Activ Fit Plus": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ Fit Plus.pdf",
          "Activ Fit Preferred": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ Fit Preferred.pdf",
          "Activ One MAX": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One MAX.pdf",
          "Activ One MAX+": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One MAX+.pdf",
          "Activ One NXT": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One NXT.pdf",
          "Activ One SAVR": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One SAVR.pdf",
          "Activ One VIP": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One VIP.pdf",
          "Activ One VIP+": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ One VIP+.pdf",
          "Activ Assured diamond-Brochure": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ+Assured+diamond-Brochure.pdf",
          "Activ+Care-Brochure": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ+Care-Brochure.pdf",
          "Activ+Care-Clasic": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ+Care-Clasic.pdf",
          "Activ+Health+Platinum-Brochure": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ+Health+Platinum-Brochure.pdf",
          "Activ+Health+Platinum+Enhanced-Brochure": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Activ+Health+Platinum+Enhanced-Brochure.pdf",
          "Super Health Plus Top-Up": "/Documents/HealthInsurance/ADITYA BIRLA/View Policy Brochure/Super Health Plus Top-Up.pdf",
  
        },
        "Apollo Munich (now HDFC ERGO)" :{
          "Easy Health Exclusive":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Easy Health Exclusive.pdf",
          "Easy Health Premium":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Easy Health Premium.pdf",
          "Easy Health Standard":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Easy Health Standard.pdf",
          "Energy Gold":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Energy Gold.pdf",
          "Energy Silver":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Energy Silver.pdf",
          "Optima Senior":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Optima Senior.pdf",
          "Optima+Restore-Brochure":"/Documents/HealthInsurance/Apollo Munich (now HDFC ERGO)/View Policy Brochure/Optima+Restore-Brochure.pdf"
        },
        "Bajaj Allianz" : {
          "Health Care Supreme Smart":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Care Supreme Smart.pdf",
          "Health Care Supreme Ultimo":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Care Supreme Ultimo.pdf",
          "Health Care Supreme Vital":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Care Supreme Vital.pdf",
          "Health Ensure Family Plan":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Ensure Family Plan.pdf",
          "Health Guard Gold":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Guard Gold.pdf",
          "Health Guard Platinum":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Guard Platinum.pdf",
          "Health Guard Silver":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Health Guard Silver.pdf",
          "Silver Health":"/Documents/HealthInsurance/Bajaj Allianz/View Policy Brochure/Silver Health.pdf",
        },
        "Bharti Axa" : {
          "Smart Super Health Assure":"/Documents/HealthInsurance/Bharti Axa/Policy Wording/Smart Super Health Assure.pdf",
          "Smart Super Health":"/Documents/HealthInsurance/Bharti Axa/Policy Wording/Smart Super Health.pdf",
          "Smart Super Top-up":"/Documents/HealthInsurance/Bharti Axa/View Policy Brochure/Smart Super Top-up.pdf",
        },
        "Care" : {
          "Care Advantage":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Advantage.pdf",
          "Care Classic":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Classic.pdf",
          "Care Freedom plan":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Freedom plan.pdf",
          "Care Heart":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Heart.pdf",
          "Care Plus Complete":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Plus Complete.pdf",
          "Care Plus Youth":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Plus Youth.pdf",
          "Care Senior":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Senior.pdf",
          "Care Supreme":"/Documents/HealthInsurance/Care/View Policy Brochure/Care Supreme.pdf",
          "Care":"/Documents/HealthInsurance/Care/View Policy Brochure/Care.pdf",
          "Enhance Super Top-up":"/Documents/HealthInsurance/Care/View Policy Brochure/Enhance Super Top-up.pdf",
          "Senior Health Advantage":"/Documents/HealthInsurance/Care/View Policy Brochure/Senior Health Advantage.pdf",
        },
        "Digit" : {
          "Digit Insurance Comfort Option" :"/Documents/HealthInsurance/Digit/Policy Wording/Digit Insurance Comfort Option.pdf",
          "Digit Insurance Smart Option" : "/Documents/HealthInsurance/Digit/Policy Wording/Digit Insurance Smart Option.pdf",
          "Double Wallet" : "/Documents/HealthInsurance/Digit/View Policy Brochure/Double Wallet.pdf",
          "Infinity Wallet" : "/Documents/HealthInsurance/Digit/View Policy Brochure/Infinity Wallet.pdf",
          "Worldwide Treatment" : "/Documents/HealthInsurance/Digit/View Policy Brochure/Worldwide Treatment.pdf",
        },
        "Edelweiss" : {
          "Health Insurance Gold" : "/Documents/HealthInsurance/Edelweiss/Policy Wording/Health Insurance Gold.pdf",
          "Health Insurance Platinum" : "/Documents/HealthInsurance/Edelweiss/Policy Wording/Health Insurance Platinum.pdf",
          "Health Insurance Silver" : "/Documents/HealthInsurance/Edelweiss/Policy Wording/Health Insurance Silver.pdf",
        },
        "HDFC Ergo" : {
          "Energy Gold" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Energy Gold.pdf",
          "Energy Silver" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Energy Silver.pdf",
          "myHealth Koti Suraksha" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/myHealth Koti Suraksha.pdf",
          "myHealth Medisure Super Top-up" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/myHealth Medisure Super Top-up.pdf",
          "myHealth Suraksha Gold" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/myHealth Suraksha Gold.pdf",
          "myHealth Suraksha Platinum" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/myHealth Suraksha Platinum.pdf",
          "myHealth Suraksha Silver" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/myHealth Suraksha Silver.pdf",
          "Optima Restore" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Optima Restore.pdf",
          "Optima Secure Global Plus" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Optima Secure Global Plus.pdf",
          "Optima Secure Global" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Optima Secure Global.pdf",
          "Optima Secure" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Optima Secure.pdf",
          "Optima Super Secure" : "/Documents/HealthInsurance/HDFC Ergo/View Policy Brochure/Optima Super Secure.pdf",
        },
        "ICICI Lombard" : {
          "iHealth Plus" : "/Documents/HealthInsurance/ICICI Lombard/Policy Wording/iHealth Plus.pdf",
          "iHealth" : "/Documents/HealthInsurance/ICICI Lombard/Policy Wording/iHealth.pdf",
          "Golden Shield" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Golden Shield.pdf",
          "Health Booster Super Top-up" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Health Booster Super Top-up.pdf",
          "Health Elite Plus" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Health Elite Plus.pdf",
          "Health Shield 360 Retail" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Health Shield 360 Retail.pdf",
          "Health Shield 360" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Health Shield 360.pdf",
          "Max Protect Classic" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Max Protect Classic.pdf",
          "Max Protect Premium" : "/Documents/HealthInsurance/ICICI Lombard/View Policy Brochure/Max Protect Premium.pdf",
        },
        "iffco Tokio" : {
          "Family+Health+Protector-+Policy+Brochure" : "/Documents/HealthInsurance/iffco Tokio/View Policy Brochure/Family+Health+Protector-+Policy+Brochure.pdf",
          "Individual Health Protector" : "/Documents/HealthInsurance/iffco Tokio/View Policy Brochure/Individual Health Protector.pdf",
        },
        "Manipal Cigma" : {
          "LifeTime Health Global" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/LifeTime Health Global.pdf",
          "LifeTime Health" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/LifeTime Health.pdf",
          "ProHealth Accumulate" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Accumulate.pdf",
          "ProHealth Plus" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Plus.pdf",
          "ProHealth Preferred" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Preferred.pdf",
          "ProHealth Premier" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Premier.pdf",
          "ProHealth Prime Active" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Prime Active.pdf",
          "ProHealth Prime Advantage" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Prime Advantage.pdf",
          "ProHealth Prime Protect" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Prime Protect.pdf",
          "ProHealth Prime Senior Classic" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Prime Senior Classic.pdf",
          "ProHealth Prime Senior Elite" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Prime Senior Elite.pdf",
          "ProHealth Protect" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Protect.pdf",
          "ProHealth Select" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/ProHealth Select.pdf",
          "SecureHealth" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/SecureHealth.pdf",
          "Super Top-up" : "/Documents/HealthInsurance/Manipal Cigma/View Policy Brochure/Super Top-up.pdf",
        },
        "National Insurance" : {
          "National Mediclaim Plus policy" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Mediclaim Plus policy.pdf",
          "National Mediclaim policy" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Mediclaim policy.pdf",
          "National Parivar Mediclaim Plus policy" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Parivar Mediclaim Plus policy.pdf",
          "National Parivar Mediclaim policy" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Parivar Mediclaim policy.pdf",
          "National Senior Citizen Mediclaim policy" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Senior Citizen Mediclaim policy.pdf",
          "National Super Top-up Mediclaim" : "/Documents/HealthInsurance/National Insurance/Policy Wording/National Super Top-up Mediclaim.pdf",
        },
        "Navi" : {
          "Navi Health" : "/Documents/HealthInsurance/Navi/View Policy Brochure/Navi Health.pdf",
        },
        "New India Assurance" : {
          "Floater Mediclaim" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/Floater Mediclaim.pdf",
          "Mediclaim" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/Mediclaim.pdf",
          "New India Top-up Mediclaim" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/New India Top-up Mediclaim.pdf",
          "Premier Mediclaim Plan" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/Premier Mediclaim Plan.pdf",
          "Senior Citizen Mediclaim" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/Senior Citizen Mediclaim.pdf",
          "Sixty Plus Mediclaim" : "/Documents/HealthInsurance/New India Assurance/Policy Wording/Sixty Plus Mediclaim.pdf",
          "Yuva Bharat Health Gold" : "/Documents/HealthInsurance/New India Assurance/View Policy Brochure/Yuva Bharat Health Gold.pdf",
          "Yuva Bharat Health Platinum" : "/Documents/HealthInsurance/New India Assurance/View Policy Brochure/Yuva Bharat Health Platinum.pdf",
          "Yuva Bharat Health" : "/Documents/HealthInsurance/New India Assurance/View Policy Brochure/Yuva Bharat Health.pdf",
        },
        "Niva Bupa (erstwhile Max Bupa)" : {
          "Aspire Diamond +" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Aspire Diamond +.pdf",
          "Aspire Gold +" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Aspire Gold +.pdf",
          "Aspire Platinum +" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Aspire Platinum +.pdf",
          "Aspire Titanium+" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Aspire Titanium+.pdf",
          "GoActive" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/GoActive.pdf",
          "Health Companion" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Companion.pdf",
          "Health Premia Gold" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Premia Gold.pdf",
          "Health Premia Platinum" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Premia Platinum.pdf",
          "Health Premia Silver" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Premia Silver.pdf",
          "Health Pulse Classic" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Pulse Classic.pdf",
          "Health Pulse Enhanced" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Pulse Enhanced.pdf",
          "Health Recharge Super Top-up" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Health Recharge Super Top-up.pdf",
          "HeartBeat Gold" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/HeartBeat Gold.pdf",
          "HeartBeat Platinum" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/HeartBeat Platinum.pdf",
          "ReAssure 2.0 Bronze+" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/ReAssure 2.0 Bronze+.pdf",
          "ReAssure 2.0 Platinum+" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/ReAssure 2.0 Platinum+.pdf",
          "ReAssure 2.0 Titanium+" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/ReAssure 2.0 Titanium+.pdf",
          "ReAssure" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/ReAssure.pdf",
          "Senior First Gold" : "/Documents/HealthInsurance/Niva Bupa (erstwhile Max Bupa)/View Policy Brochure/Senior First Gold.pdf",
        },
        "Oriental Insurance" : {
          "Happy Family Floater Policy Diamond" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Happy Family Floater Policy Diamond.pdf",
          "Happy Family Floater Policy Gold" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Happy Family Floater Policy Gold.pdf",
          "Happy Family Floater Policy Silver" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Happy Family Floater Policy Silver.pdf",
          "Health of Privileged Elders" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Health of Privileged Elders.pdf",
          "Mediclaim Insurance Policy" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Mediclaim Insurance Policy.pdf",
          "Super Health Top-up" : "/Documents/HealthInsurance/Oriental Insurance/Policy Wording/Super Health Top-up.pdf",
        },
        "Reliance" : {
          "Health Gain Plus" : "/Documents/HealthInsurance/Reliance/View Policy Brochure/Health Gain Plus.pdf",
          "Health Gain Power" : "/Documents/HealthInsurance/Reliance/View Policy Brochure/Health Gain Power.pdf",
          "Health Gain Prime" : "/Documents/HealthInsurance/Reliance/View Policy Brochure/Health Gain Prime.pdf",
          "Health Infinity" : "/Documents/HealthInsurance/Reliance/View Policy Brochure/Health Infinity.pdf",
          "Reliance Super Top-Up" : "/Documents/HealthInsurance/Reliance/View Policy Brochure/Reliance Super Top-Up.pdf",
        },
        "Royal Sundaram" : {
          "Advanced Top Up" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Advanced Top Up.pdf",
          "Family Plus" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Family Plus.pdf",
          "Lifeline Classic" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Lifeline Classic.pdf",
          "Lifeline Elite" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Lifeline Elite.pdf",
          "Lifeline Supreme" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Lifeline Supreme.pdf",
          "Multiplier Health" : "/Documents/HealthInsurance/Royal Sundaram/View Policy Brochure/Multiplier Health.pdf",
        },
        "SBI" : {
          "Arogya Plus" : "/Documents/HealthInsurance/SBI/View Policy Brochure/Arogya Plus.pdf",
          "Arogya Premier" : "/Documents/HealthInsurance/SBI/View Policy Brochure/Arogya Premier.pdf",
          "Arogya Top-up" : "/Documents/HealthInsurance/SBI/View Policy Brochure/Arogya Top-up.pdf",
          "Retail Health Policy" : "/Documents/HealthInsurance/SBI/View Policy Brochure/Retail Health Policy.pdf",
        },
        "Star Health" : {
          "Cardiac Care Platinum" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Cardiac Care Platinum.pdf",
          "Comprehensive" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Comprehensive.pdf",
          "Diabetes Safe" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Diabetes Safe.pdf",
          "Family Health Optima" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Family Health Optima.pdf",
          "Health Gain" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Health Gain.pdf",
          "Health Premier" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Health Premier.pdf",
          "Medi Classic Gold" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Medi Classic Gold.pdf",
          "Medi Classic" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Medi Classic.pdf",
          "Red Carpet Senior Citizens" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Red Carpet Senior Citizens.pdf",
          "Smart Health Pro" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Smart Health Pro.pdf",
          "Special Care Gold" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Special Care Gold.pdf",
          "Special Care" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Special Care.pdf",
          "Super Surplus Gold" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Super Surplus Gold.pdf",
          "Women Care" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Women Care.pdf",
          "Young Star" : "/Documents/HealthInsurance/Star Health/View Policy Brochure/Young Star.pdf",
        },
        "TATA AIG" : {
          "Medicare Plus Super Top-up" : "/Documents/HealthInsurance/TATA AIG/View Policy Brochure/Medicare Plus Super Top-up.pdf",
          "Medicare Premier" : "/Documents/HealthInsurance/TATA AIG/View Policy Brochure/Medicare Premier.pdf",
          "Medicare Protect" : "/Documents/HealthInsurance/TATA AIG/View Policy Brochure/Medicare Protect.pdf",
          "Medicare Senior" : "/Documents/HealthInsurance/TATA AIG/View Policy Brochure/Medicare Senior.pdf",
          "Medicare" : "/Documents/HealthInsurance/TATA AIG/View Policy Brochure/Medicare.pdf",
        },
        "United India" : {
          "Family Medicare" : "/Documents/HealthInsurance/United India/Policy Wording/Family Medicare.pdf",
          "Individual Gold Plan" : "/Documents/HealthInsurance/United India/Policy Wording/Individual Gold Plan.pdf",
          "Individual Platinum Plan" : "/Documents/HealthInsurance/United India/Policy Wording/Individual Platinum Plan.pdf",
          "Medicare Super Top-up" : "/Documents/HealthInsurance/United India/Policy Wording/Medicare Super Top-up.pdf",
          "Senior Citizen Plan" : "/Documents/HealthInsurance/United India/Policy Wording/Senior Citizen Plan.pdf",
        },
        "Universal Sompo" : {
          "Complete Healthcare Basic" : "/Documents/HealthInsurance/Universal Sompo/View Policy Brochure/Complete Healthcare Basic.pdf",
          "Complete Healthcare Essential" : "/Documents/HealthInsurance/Universal Sompo/View Policy Brochure/Complete Healthcare Essential.pdf",
          "Complete Healthcare Privilege" : "/Documents/HealthInsurance/Universal Sompo/View Policy Brochure/Complete Healthcare Privilege.pdf",
        }
      },
      "Term Insurance": {
          "Bajaj Allianz Life": {
            "ETouch-Brochure": "/Documents/TermInsurance/Bajaj Allianz Life/View Policy Brochure/ETouch-Brochure.pdf",
            "Smart Protect Goal": "/Documents/TermInsurance/Bajaj Allianz Life/View Policy Brochure/Smart Protect Goal.pdf",
          },
          "HDFC Life": {
            "Click2Protect Life": "/Documents/TermInsurance/HDFC Life/View Policy Brochure/Click2Protect Life.pdf",
            "Click2Protect Super": "/Documents/TermInsurance/HDFC Life/View Policy Brochure/Click2Protect Super.pdf",
          },
          "ICICI Prudential" : {
            "iProtect Smart" : "/Documents/TermInsurance/ICICI Prudential/View Policy Brochure/iProtect Smart.pdf"
          },
          "Max Life" : {
            "Smart Secure Plus" : "/Documents/TermInsurance/Max Life/View Policy Brochure/Smart Secure Plus.pdf",
            "Smart Total Elite Protection" : "/Documents/TermInsurance/Max Life/View Policy Brochure/Smart Total Elite Protection.pdf"
          },
          "TATA AIA" : {
            "Maha Raksha Supreme" : "/Documents/TermInsurance/TATA AIA/View Policy Brochure/Maha Raksha Supreme.pdf",
            "Sampoorna Raksha Supreme" : "/Documents/TermInsurance/TATA AIA/View Policy Brochure/Sampoorna Raksha Supreme.pdf",
            "SRS Vitality" : "/Documents/TermInsurance/TATA AIA/View Policy Brochure/SRS Vitality.pdf",
          }
        }, 
  };